### ISSUE TITLE
Unwanted marketing emails

### ISSUE THREAD

**Issue by KNejad** [SyborgStudios/overrides_tracker#4]
I'm receiving unwanted marketing emails about this gem. Is this coming directly from you or a third party? I hope you stop this type of marketing of finding people via GitHub stars to other known projects. If people do not sign up to mailing lists you shouldn't be marketing to them like that.

**Comment by SyborgStudios** [comment]
Thx, sorry. I just picked a few people randomly.

**Comment by KNejad** [comment]
@SyborgStudios, that's okay. Sorry if my message came across as a bit aggressive there. I hope you the best with your gem. I suggest though posting this on forums dedicated for this kind of thing, such as Reddit. Perhaps you'll have more luck there.
